version: '2'

services:

    # nginx: 
    #     restart: unless-stopped
    #     container_name: "nginx"
    #     build: 
    #         context: .
    #         dockerfile: ./deployment/nginx/Dockerfile
    #     ports:
    #         - 80:80
    #         - 443:443
    #     volumes:
    #         - ./deployment/nginx:/etc/nginx/conf.d
    #         - logging:/usr/share/nginx/logs
    #         - /etc/ssl:/etc/ssl
    #     depends_on:
    #         - backend
    #         - frontend
    #     networks:
    #         - front-network
    
    # frontend: 
    #     restart: unless-stopped
    #     container_name: "frontend"
    #     build: 
    #         context: .
    #         dockerfile: ./deployment/frontend/Dockerfile
    #     ports:
    #         - 3000:3000
    #     depends_on:
    #         - backend
    #     links:
    #         - backend
    #     networks:
    #         - front-network
    
    backendDB:
        restart: unless-stopped
        image: postgres:12.10
        volumes:
            - database:/var/lib/postgresql/data
        # env_file:
                # - ./deployments/config.env              # <--- you have to change in this file.
        environment:
            - POSTGRES_DB=ft_transcendence
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
        ports:
            - 5555:5432
    # pgadmin:
    #     container_name: pgadmin4_container
    #     image: dpage/pgadmin4
    #     restart: always
    #     environment:
    #       PGADMIN_DEFAULT_EMAIL: admin@admin.com
    #       PGADMIN_DEFAULT_PASSWORD: root
    #     networks:
    #         - db-network
    #     ports:
    #       - "5050:80"

volumes:
    database: {}

# networks:
#     front-network:
#     back-network: