version: '2'

services:
    frontend:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./deployments/frontend/Dockerfile
        ports:
            - 3000:3000
        depends_on:
            - backend
        links:
            - backend
        networks:
            - front-network

    backend:
        container_name: nest-api
        build:
            context: .
            dockerfile: ./deployments/backend/Dockerfile
        ports:
            - 9000:9000
        depends_on:
            - db
        env_file:
            - ./deployments/backend/config.env
        networks:
            - front-network
            - back-network
    db:
        restart: unless-stopped
        image: postgres:12.10
        volumes:
            - database:/var/lib/postgresql/data
            # env_file:
            # - ./deployments/config.env              # <--- you have to change in this file.
        environment:
            - POSTGRES_DB=ft_transcendence
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
        ports:
            - 5555:5432
        networks:
            - back-network

volumes:
    database: {}

networks:
    front-network:
    back-network:
