version: '2'

services:
    backendDB:
        restart: unless-stopped
        image: postgres:12.10
        volumes:
            - database:/var/lib/postgresql/data
        # env_file:
                # - ./deployments/config.env              # <--- you have to change in this file.
        environment:
            - POSTGRES_DB=ft_transcendence
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
        ports:
            - 5555:5432
        networks:
            - back-network
    # api:
    #     build:
    #         context: .
    #         dockerfile: ./deployments/backend/Dockerfile
    #         target: development
    #     depends_on:
    #         - backendDB
    #     volumes:
    #         - .:/app
    #     env_file:
    #         - ./backend/.env
    #     command: npm run start:dev
    #     ports:
    #         - 9000:9000
    #     networks:
    #         - back-network

volumes:
    database: {}

networks:
#     front-network:
    back-network: